blog/urls.py
from django.urls import path

from . import views



urlpatterns = [

path('', views.post_list, name='post_list'),
#path('',  PostListView.as_view() , name='post_list'),
path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/',  views.post_detail, name='post_detail'),

]

gv_project/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include
from marketplace import views as MarketplaceViews


urlpatterns = [
    
    # path('jet/', include('jet.urls', 'jet')),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    
    path('admin/', admin.site.urls),
    
    # User management
    
    path('accounts/', include('accounts.urls')),
   
    
    # Local apps
    path('', include('pages.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('comments/', include('django_comments_xtd.urls')),
    
    #path('doctors/', include('doctors.urls'))
    path('blog/', include('blog.urls')),
    path('marketplace/', include('marketplace.urls')),
    
    path('laboratories/', include('laboratories.urls')),
    
     # CART
    path('cart/', MarketplaceViews.cart, name='cart'),
    # SEARCH
    path('search/', MarketplaceViews.search, name='search'),

    # CHECKOUT
    path('checkout/', MarketplaceViews.checkout, name='checkout'),

    # ORDERS
    path('orders/', include('orders.urls')),
    
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header =  "Getvet Admin"
admin.site.site_title =   "Getvet Admin Portal"
admin.site.index_title = "Welcome to Getvet Portal"

marketplace/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.marketplace, name='marketplace'),
    
    path('<slug:doctor_slug>/', views.doctor_detail, name='doctor_detail'),

     # ADD TO CART
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
     # DECREASE CART
    path('decrease_cart/<int:item_id>/', views.decrease_cart, name='decrease_cart'),
     # DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    
    path('chat/', include('chatapp.urls')),
    
    
]

marketplace/models.py
from django.db import models

from accounts.models import User
from service.models import ConsultationItem


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    consultationitem = models.ForeignKey(ConsultationItem, on_delete=models.CASCADE)
    session = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.user


class Tax(models.Model):
    tax_type = models.CharField(max_length=20, unique=True)
    tax_percentage = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax Percentage (%)')
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Taxes'

    def __str__(self):
        return self.tax_type

orders/models.py
import json
from django.db import models
from accounts.models import User
from service.models import ConsultationItem
from doctors.models import Doctor


request_object = ''

class Payment(models.Model):
    PAYMENT_METHOD = (
        ('Monnify', 'Monnify'),
        ('Paystack', 'Paystack'), # Only for Indian Students.
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    receiver= models.ForeignKey(Doctor, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.FloatField()
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id
    
    class meta:
        ordering = ['-created_at']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    doctors = models.ManyToManyField(Doctor, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}", null=True)
    total_data = models.JSONField(blank=True, null=True)
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def order_placed_to(self):
        return ", ".join([str(i) for i in self.doctors.all()])

    def get_total_by_doctor(self):
        doctor = Doctor.objects.get(user=request_object.user)
        subtotal = 0
        tax = 0
        tax_dict = {}
        if self.total_data:
            total_data = json.loads(self.total_data)
            data = total_data.get(str(doctor.id))
            
            
            for key, val in data.items():
                subtotal += float(key)
                val = val.replace("'", '"')
                val = json.loads(val)
                tax_dict.update(val)

                # calculate tax
                # {'CGST': {'9.00': '6.03'}, 'SGST': {'7.00': '4.69'}}
                for i in val:
                    for j in val[i]:
                        tax += float(val[i][j])
        grand_total = float(subtotal) + float(tax)
        context = {
            'subtotal': subtotal,
            'tax_dict': tax_dict, 
            'grand_total': grand_total,
        }

        return context

    def __str__(self):
        return self.order_number


class OrderedItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(ConsultationItem, on_delete=models.CASCADE)
    session = models.IntegerField()
    fee = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item.type.name

marketplace/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from accounts.models import UserProfile
from .context_processors import get_cart_counter, get_cart_amounts
from service.models import Service, ConsultationItem, Consultation
from orders.forms import OrderForm
from doctors.models import  Doctor, OpeningHour
from django.db.models import Prefetch
from .models import Cart 
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# from django.contrib.gis.geos import GEOSGeometry
# from django.contrib.gis.measure import D # ``D`` is a shortcut for ``Distance``
# from django.contrib.gis.db.models.functions import Distance
from django.core.paginator import Paginator
from datetime import date, datetime
# from orders.forms import OrderForm


def marketplace(request):
    doctors = Doctor.objects.filter(is_approved=True, user__is_active=True)
    doctor_count = doctors.count()
    paginator = Paginator(doctors, 20)  # Show 25 contacts per page.
    
    page_number = request.GET.get("page", 1)
    page_obj = paginator.get_page(page_number)
    
    context = {
        'doctors': doctors,
        'doctor_count': doctor_count,
        'page_obj': page_obj
    }
    return render(request, 'marketplace/doctor_listings.html', context)


def doctor_detail(request, doctor_slug):
    doctor = get_object_or_404(Doctor, doctor_slug=doctor_slug)

    consultationItems = ConsultationItem.objects.order_by('type__name').filter(owner=doctor, is_available=True)
    

    opening_hours = OpeningHour.objects.filter(doctor=doctor).order_by('day', 'from_hour')
    
    # Check current day's opening hours.
    today_date = date.today()
    today = today_date.isoweekday()
    
    current_opening_hours = OpeningHour.objects.filter(doctor=doctor, day=today)
    if request.user.is_authenticated:
            cart_items = Cart.objects.filter(user=request.user)
    else:
            cart_items = None
    context = {
        'doctor': doctor,
        'consultationItems': consultationItems,
        'cart_items': cart_items,
        'opening_hours': opening_hours,
        'current_opening_hours': current_opening_hours,
    }
    return render(request, 'marketplace/doctor_details.html', context)


def add_to_cart(request, item_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # Check if the food item exists
            try:
                consultationitem = ConsultationItem.objects.get(id=item_id)
                # Check if the user has already added that food to the cart
                try:
                    chkCart = Cart.objects.get(user=request.user,  consultationitem= consultationitem)
                    # Increase the cart sessin
                    chkCart.session += 1
                    chkCart.save()
                    return JsonResponse({'status': 'Success', 'message': 'Increased the cart session', 'cart_counter': get_cart_counter(request), 'ses': chkCart.session, 'cart_amount': get_cart_amounts(request)})
                except:
                    chkCart = Cart.objects.create(user=request.user,  consultationitem= consultationitem, session=1)
                    return JsonResponse({'status': 'Success', 'message': 'Added the item to the cart', 'cart_counter': get_cart_counter(request), 'ses': chkCart.session, 'cart_amount': get_cart_amounts(request)})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'This item does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})
        
    else:
        return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})


def decrease_cart(request, item_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # Check if the  item exists
            try:
                consultationitem = ConsultationItem.objects.get(id=item_id)
                # Check if the user has already added that food to the cart
                try:
                    chkCart = Cart.objects.get(user=request.user, consultationitem=consultationitem)
                    if chkCart.session > 1:
                        # decrease the cart quantity
                        chkCart.session -= 1
                        chkCart.save()
                    else:
                        chkCart.delete()
                        chkCart.session = 0
                    return JsonResponse({'status': 'Success', 'cart_counter': get_cart_counter(request), 'ses': chkCart.session, 'cart_amount': get_cart_amounts(request)})
                except:
                    return JsonResponse({'status': 'Failed', 'message': 'You do not have this item in your cart!'})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'This item does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})
        
    else:
        return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})


@login_required(login_url = 'login')
def cart(request):
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    context = {
        'cart_items': cart_items,
    }
    return render(request, 'marketplace/cart.html', context)


def delete_cart(request, cart_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            try:
                # Check if the cart item exists
                cart_item = Cart.objects.get(user=request.user, id=cart_id)
                if cart_item:
                    cart_item.delete()
                    return JsonResponse({'status': 'Success', 'message': 'Cart item has been deleted!', 'cart_counter': get_cart_counter(request), 'cart_amount': get_cart_amounts(request)})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'Cart Item does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})


def search(request):
    # if not 'address' in request.GET:
    #     return redirect('marketplace')
    # else:
    #     address = request.GET['address']
    #     latitude = request.GET['lat']
    #     longitude = request.GET['lng']
    #     radius = request.GET['radius']
    #     keyword = request.GET['keyword']

    #     # get doctor ids that has the  item the user is looking for
    #     fetch_doctors_by_consultationitems = ConsultationItem.objects.filter(type__icontains=keyword, is_available=True).values_list('owner', flat=True)
        
    #     doctors = Doctor.objects.filter(Q(id__in=fetch_doctors_by_consultationitems) | Q(doctor_slug__icontains=keyword, is_approved=True, user__is_active=True))
    #     if latitude and longitude and radius:
    #         pnt = GEOSGeometry('POINT(%s %s)' % (longitude, latitude))

    #         doctors = Doctor.objects.filter(Q(id__in=fetch_doctors_by_consultationitems) | Q(doctor_slug__icontains=keyword, is_approved=True, user__is_active=True),
    #         user_profile__location__distance_lte=(pnt, D(km=radius))
    #         ).annotate(distance=Distance("user_profile__location", pnt)).order_by("distance")

    #         for d in doctors:
    #             d.kms = round(d.distance.km, 1)
    #     doctor_count = doctors.count()
    if not 'address' in request.GET:
         return redirect('marketplace')
    else:
        
        location = request.GET['address']
        keyword = request.GET['keyword']
        
        # doctors = Doctor.objects.filter(is_approved=True, user__is_active=True).filter(Q(specialty__name=keyword) | Q(state_of_practice__icontains=location)).distinct()  
        
        doctors = Doctor.objects.filter(is_approved=True, user__is_active=True).filter(Q(specialty__name__icontains=keyword, state_of_practice__icontains=location)).distinct()  
        
        doctors_count = doctors.count() 
        
        print(doctors)  
        context = {
            
            'doctors': doctors,
            'doctors_count':  doctors_count,
                
            }


        return render(request, 'marketplace/search_listings.html', context) #context


@login_required(login_url='login')
def checkout(request):
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect('marketplace')
    
    user_profile = UserProfile.objects.get(user=request.user)
    default_values = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        #'phone': request.user.phone_number,
        'email': request.user.email,
        'address': user_profile.address,
        'country': user_profile.country,
        'state': user_profile.state,
        'city': user_profile.city,
        'pin_code': user_profile.pin_code,
    }
    form = OrderForm(initial=default_values)
    context = {
        'form': form,
        'cart_items': cart_items,
    }
    return render(request, 'marketplace/checkout.html', context)

templates/marketplace/doctor_listings.html
{% extends '../base.html' %}
{% load static %}

{% block title %}About{% endblock title %}

 <!-- LOAD HEADER HERE -->
 {% block header %}

 {% include '../includes/header.html' %}

 {% endblock header %}

{% block content %}


<main>
   
    <section class="section-header pb-5 pb-lg-6 mb-4 mb-lg-6 bg-primary text-white">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-10 text-center">
                     <h1 class="mb-3 h3">Search for Doctors</h1>
                    <p class=" px-lg-5 mb-5">Quicky search for doctors near you. You can also search by doctor's specialty or location.</p>
                    <form action="{% url 'search' %}" method="GET">
                        <div class="form-group bg-white shadow-soft mb-4 px-3 py-2">
                            <div class="row align-items-center">
                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                    <div class="input-group input-group-merge shadow-none">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-transparent border-0"><i class="fas fa-search"></i></span>
                                        </div>
                                        <input type="text" name="keyword" class="form-control border-0 form-control-flush shadow-none pb-2" placeholder="Search e.g dog..." required />
                                    </div>
                                </div>
                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                    <div class="input-group input-group-merge shadow-none">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-transparent border-0"><i class="fas fa-map-marker-alt"></i></span>
                                        </div>
                                        <input type="text" name="address" id="id_address" class="form-control border-0 form-control-flush shadow-none pb-2" placeholder="Location..." required />
                                        {% comment %} <input type="hidden" name="lat" value="" id="id_latitude">
                                        <input type="hidden" name="lng" value="" id="id_longitude"> {% endcomment %}
                                    </div>
                                </div>
                                {% comment %} <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="input-group input-group-merge shadow-none">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-transparent border-0"><i class="fab fa-chrome"></i></span>
                                        </div>
                                        <select name="radius" id="radius" class="form-control border-0 form-control-flush shadow-none pb-2" required>
                                            <option value="" selected>Radius</option>
                                            <option value="5">5km</option>
                                            <option value="10">10km</option>
                                            <option value="15">15km</option>
                                            <option value="25">25km</option>
                                            <option value="50">50km</option>
                                            <option value="75">75km</option>
                                            <option value="100">100km</option>
                                        </select> 
                                    </div>
                                </div> {% endcomment %}
                                <div class="col-auto"><button type="submit" class="btn btn-block btn-primary rounded-pill" value="Search">Search</button></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> 
    </section>
    
    <section class="section section-lg pb-5 bg-soft">
        <div class="container">
           {% if doctors_count == True %}
             <div class="row justify-content-center mb-4 mb-lg-5">
                <div class="col"><h2 class="h5">{{doctors_count}} result found</h2></div>
            </div>
            {%else%}
             <div class="row justify-content-center mb-4 mb-lg-5">
                <div class="col"><h2 class="h5">Available Doctors</h2></div>
            </div>
            {% endif %}
            <div class="row">
                {% for doctor in page_obj %}
                <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0 col-xs-6">
                    <div class="card bg-white border-light shadow-soft p-3">
                        <div class="card-header p-4">
                            {% if doctor.is_online %}
                            <span class="shape-xs small mr-1 bi bi-circle-fill" style="color:#05a677; font-size: 50%;"></span> <span class="font-weight-normal small mr-3">online</span>
                            {% else %}
                            <span class="shape-xs mr-1 bi bi-circle-fill" style="color:#ee5050; font-size:50%;"></span> <span class="font-weight-normal small mr-3">offline</span>
                            {% endif %}
                            <h3 class="mb-3 h6">Dr. {{doctor.user_profile }}</h3>
                            <div class="d-flex small mb-2">
                                <a href="#" class="text-gray">
                                    <span class="icon-primary"><i class="fas fa-map-marker-alt"></i></span><span class="ml-2">{{doctor.state_of_practice }}</span>
                                </a>
                                
                            </div>
                           
                            <div class="d-flex small">
                                <a href="#" class="text-gray">
                                    <span class="icon-primary"><i class="fas fa-clock"></i></span><span class="ml-2">{{doctor.experience}}</span>
                                </a>
                                
                            </div>
                          
                            <div class="d-flex small">
                            {% for specialty in doctor.specialty.all%}
                            <span class="badge badge-pill badge-primary mt-2">{{specialty}}</span>
                            {% endfor %}
                            {% comment %} <p class="mb-4 small"><strong>Specialty:</strong></p> {% endcomment %}
                            </div>
                        </div>
                        <div class="card-body px-4 pt-0">
                            <div class="d-flex">
                                {% if doctor.user_profile.profile_picture %}
                                <div class="avatar-lg"><img class="rounded-circle" src="{{ doctor.user_profile.profile_picture.url }}" alt="avatar" /></div>
                                {% else %}   
                                <div class="avatar-lg"><img class="rounded-circle" src="{% static './assets/img/default_profile_pic.png' %}" alt="avatar" /></div>
                                {% endif %}

                                <a href="{% url 'doctor_detail' doctor.doctor_slug %}" class="btn btn-xs btn-secondary align-items-center justify-content-center animate-up-2 px-2 py-2 ml-3"> <span class="mr-2"><span class="fas fa-clipboard-list"></span></span>View Details</a>   
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

     <div class="d-flex justify-content-center w-100">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                {% endif %}
                {% for number in page_obj.paginator.page_range %}
                <li class="page-item"><a class="page-link" href="?page={{number}}">{{number}}</a></li>
                {% endfor %}
                 {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
     </div>
</main>


{% endblock content %}


{%block footer%}

{% include '../includes/footer.html' %}
{% endblock footer%}



                                            